In [92]:
import pandas as pd
import numpy as np

df = pd.read_csv('pedidos_narashop.csv', sep=';')

In [93]:
df['valor_total'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

In [94]:
# separando o total de cada categoria 
df_categoria_receita = df.groupby('categoria')['valor_total'].sum().reset_index().sort_values(by='valor_total', ascending=False)
df_categoria_receita

          categoria  valor_total
2       Eletrônicos  37037997.65
3          Esportes   8058234.35
1  Casa e Decoração   3333395.06
0        Brinquedos   2306126.65

In [95]:
# Status do pedido
df_entregue_ac500 = df.loc[(df['status_pedido'] == 'Entregue') & (df['valor_total'] > 500)]
df_entregue_ac500

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
19,10020,Renato Cavalcante,Eletrônicos,Smartwatch,Entregue,3,461.46,3,1384.38
25,10026,Larissa Nunes,Brinquedos,Telescópio Infantil,Entregue,5,487.03,2,2435.15
...,...,...,...,...,...,...,...,...,...
19987,29988,Sérgio Machado,Casa e Decoração,Fritadeira Air Fryer,Entregue,5,403.51,8,2017.55
19989,29990,Diego Fernandes,Esportes,Bicicleta Ergométrica,Entregue,1,1235.61,10,1235.61
19992,29993,Larissa Nunes,Casa e Decoração,Tapete Sala,Entregue,3,279.57,18,838.71
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36

In [96]:
df_produtos = df.groupby('produto')['valor_total'].sum().reset_index().sort_values(by='valor_total', ascending=False)
array_produtos_valor_total = np.array(df_produtos['valor_total'])
media_produto = np.mean(array_produtos_valor_total)
mediana_produto = np.median(array_produtos_valor_total)
distancia = round(((media_produto - mediana_produto) /mediana_produto) * 100 ,2)
q1_produtos = np.percentile(array_produtos_valor_total, 25)
q3_produtos = np.percentile(array_produtos_valor_total, 75)
iqr_produtos = q3_produtos - q1_produtos
superior_produtos = q3_produtos + (1.5 * iqr_produtos)
inferior_produtos = q1_produtos - (1.5 * iqr_produtos) # Negativo logo desnecessário 
print(q1_produtos, q3_produtos, superior_produtos)

73869.3475 367550.645 808072.59125

In [97]:
df_menor_q1 = df_produtos.loc[df_produtos['valor_total'] < q1_produtos].sort_values(by='valor_total')
df_menor_q1

                     produto  valor_total
24       Massinha de Modelar     17550.06
9             Corda de Pular     23767.20
32            Porta-Retratos     26224.38
28    Organizador de Gavetas     36586.33
42            Tapete de Yoga     50209.91
30                   Pelúcia     51088.67
34  Quebra-Cabeça 1000 peças     51701.41
10         Difusor de Aromas     57532.21
14           Garrafa Térmica     63532.51
6        Carregador Portátil     64156.00
8        Conjunto de Toalhas     70889.32
0          Bermuda Esportiva     73266.61

In [98]:
df_menor_q3 = df_produtos.loc[df_produtos['valor_total'] > q3_produtos]
df_menor_q3

                  produto  valor_total
27               Notebook  15091721.74
37               Smart TV   8474171.95
38             Smartphone   6806241.19
1   Bicicleta Ergométrica   5949159.26
40                 Tablet   3258725.63
39             Smartwatch   1344856.80
13   Fritadeira Air Fryer    980636.15
17        Jogo de Panelas    760544.58
36            SSD Externo    719921.59
45       Tênis de Corrida    696912.40
44    Telescópio Infantil    409588.10
43       Teclado Mecânico    372827.72

In [103]:
outlier_sup_produtos = df_produtos.loc[df_produtos['valor_total'] > superior_produtos]
outlier_sup_produtos

                  produto  valor_total
27               Notebook  15091721.74
37               Smart TV   8474171.95
38             Smartphone   6806241.19
1   Bicicleta Ergométrica   5949159.26
40                 Tablet   3258725.63
39             Smartwatch   1344856.80
13   Fritadeira Air Fryer    980636.15

In [99]:
df_valor_total_vendedor = df.groupby('vendedor')['valor_total'].sum().reset_index().sort_values(by='valor_total', ascending=False)
array_valor_total_vendedor = np.array(df_valor_total_vendedor['valor_total'])
q1_vendedor = np.percentile(array_valor_total_vendedor, 25)
# q2 = np.percentile(array_valor_total_vendedor, 50)
q3_vendedor = np.percentile(array_valor_total_vendedor, 75)
iqr_vendedor = q3_produtos - q1_produtos
superior_vendedor = q3_vendedor + (1.5 * iqr_vendedor)
inferior_vendedor = q1_vendedor - (1.5 * iqr_vendedor) # Valor negativo logo não conta
print(q1_vendedor, q3_vendedor)
print(superior_vendedor, inferior_produtos)

376922.66250000003 973621.695
1414143.6412499999 -366652.59875

In [100]:
df_vendedor_menor_q1 = df_valor_total_vendedor.loc[df_valor_total_vendedor['valor_total'] < q1_vendedor]
df_vendedor_menor_q1

             vendedor  valor_total
19       Fábio Araújo    373244.59
29    Mariana Correia    363231.71
22     Isabela Mendes    347744.74
48     Vinícius Lopes    327272.71
14    Eduardo Freitas    291632.72
10  Cristiane Tavares    206953.21
11      Danilo Campos    163822.10
30     Matheus Borges    154941.79
45        Tiago Moura    142846.86
15  Elaine Figueiredo    127838.65
47       Vera Andrade    115512.99
36     Raquel Esteves     85104.85
0   Alexandre Lacerda     62427.49

In [101]:
df_vendedor_maior_q3 = df_valor_total_vendedor.loc[df_valor_total_vendedor['valor_total'] > q3_produtos]
df_vendedor_maior_q3

             vendedor  valor_total
3            Ana Lima   3950687.71
35    Rafael Oliveira   3934561.13
23    Juliana Martins   3226272.18
12    Diego Fernandes   3180786.47
8        Carlos Souza   3065164.09
32     Patrícia Rocha   3008726.29
6         Bruno Alves   2894957.47
17     Fernanda Costa   2855540.29
46      Vanessa Sousa   1118480.12
13      Débora Vieira   1061689.40
7      Camila Pereira   1046413.86
18     Flávia Azevedo   1035353.05
43      Tatiane Cunha    975057.20
34  Priscila Teixeira    969315.18
44      Thiago Santos    936837.28
2        Amanda Silva    900957.64
28   Marcelo Monteiro    884924.36
31    Natália Barbosa    878844.60
24      Larissa Nunes    873830.90
25       Leandro Reis    824988.84
5     Bianca Carvalho    822331.10
33   Paulo Nascimento    801924.38
1      Aline Ferreira    733366.10
39    Rodrigo Batista    732576.76
4       Anderson Cruz    714554.83
9       Claudia Ramos    706470.26
41      Simone Castro    664679.66
49     Willian Duarte    656240.17
42     Sérgio Machado    643342.60
26    Letícia Moreira    581852.56
40       Sabrina Melo    575799.70
38    Roberto Cardoso    480599.38
37  Renato Cavalcante    470882.91
21      Henrique Dias    462361.32
20      Gustavo Pinto    461151.06
27      Lucas Ribeiro    453701.57
16       Felipe Gomes    387956.88
19       Fábio Araújo    373244.59

In [104]:
outlier_sup_vendedor = df_valor_total_vendedor.loc[df_valor_total_vendedor['valor_total'] > superior_vendedor]
outlier_sup_vendedor

           vendedor  valor_total
3          Ana Lima   3950687.71
35  Rafael Oliveira   3934561.13
23  Juliana Martins   3226272.18
12  Diego Fernandes   3180786.47
8      Carlos Souza   3065164.09
32   Patrícia Rocha   3008726.29
6       Bruno Alves   2894957.47
17   Fernanda Costa   2855540.29

In [102]:
array_total = np.array(df['valor_total'])
media_total = np.mean(array_total)
mediana_total = np.median(array_total)
distancia_total = round(((media_total - mediana_total) /mediana_total) * 100 , 2)
print(f"Média total: {media_total} \nMediana Total: {mediana_total} \nDistancia entre média e mediana: {distancia_total}")

Média total: 2536.7876855
Mediana Total: 882.635
Distancia entre média e mediana: 187.41